version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - "5672:5672"
    - "15672:15672"

#  nats:
#    image: nats:1.3.0-linux
#    container_name: nats
#    ports:
#    - "4222:4222"
#    - "8222:8222"
#    - "6222:6222"

  nats-streaming-server:
    image: nats-streaming:0.15.1-linux
    container_name: nats-streaming-server
    ports:
    - "4222:4222"
    - "4223:4223"
    - "8223:8223"

  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
    - "4160:4160"
    - "4161:4161"

  nsqd:
    image: nsqio/nsq
    container_name: nats-streaming
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
    - nsqlookupd
    ports:
    - "4150:4150"
    - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
    - nsqlookupd
    ports:
    - "4171:4171"