version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - "5672:5672"
    - "15672:15672"

#  nats:
#    image: nats:1.3.0-linux
#    container_name: nats
#    ports:
#    - "8222:8222"
#    - "6222:6222"

  nats-streaming-server:
    image: nats-streaming:0.11.0-linux
    container_name: nats-streaming
    ports:
    - "4222:4222"
    - "4223:4223"
    - "8223:8223"
